### ISSUE TITLE
Requirements missing and not mentioned

### ISSUE THREAD

**Issue by DodoLeDev** [alexdelorenzo/cast_control#19]
When installing cast_control with pip(x), I faced a fatal error:
```
Package gobject-introspection-1.0 was not found in the pkg-config search path.
Package 'gobject-introspection-1.0', required by 'virtual:world', not found
```
Considering this, I decided to install the package `gobject-introspection`, then try reinstalling cast_control, result: **it worked**!

However, in your README, you only mentioned to install the **python-gobject** package, which only has `gobject-introspection-runtime` and `python` as dependencies, so `gobject-introspection` remains missing!

**Could you please update your README document to help new users to face this error?**

**Comment by DodoLeDev** [comment]
I am under **Arch Linux**, if you want to know...

**Comment by alexdelorenzo** [comment]
Hi @DodoLeDev, thanks for point this out. I'll make a note of it in the README.

Does installing Cast Control like this:
```bash
$ python3 -m pip install --upgrade cast_control
```
Or:
```bash
$ git clone https://github.com/alexdelorenzo/cast_control.git
$ cd cast_control
$ python3 -m pip install .
```

Work for you without first having to install `gobject-introspection`?

**Comment by alexdelorenzo** [comment]
> I am under **Arch Linux**, if you want to know...

@yochananmarqos was kind enough to package Cast Control for the AUR here: https://aur.archlinux.org/packages/cast_control/

You can use your preferred AUR installer to install Cast Control and keep it up to date. The package manager will handle any of the dependencies needed.

**Comment by alexdelorenzo** [comment]
I added `gobject-introspection` to the README for Arch users. I'm going to close this issue for now, but if you have any further input concerning my comments above, please feel free to share it :)
