### ISSUE TITLE
AUR package: missing or not found dependencies

### ISSUE THREAD

**Issue by FieryMewtwo** [alexdelorenzo/cast_control#23]
Trying to install from AUR gives this error:

```bash
[sataa@SusBook cast_control]$ makepkg -si
==> Making package: cast_control 1:0.11.8.post0-3 (Sat 03 Jun 2023 02:42:17 PM EDT)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: python-aiopath
error: target not found: python-daemons
error: target not found: python-mpris_server
error: target not found: python-pychromecast>=9.2.0
error: target not found: python-pychromecast<9.3.0
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> python-aiopath
  -> python-appdirs
  -> python-click
  -> python-daemons
  -> python-mpris_server
  -> python-pychromecast>=9.2.0
  -> python-pychromecast<9.3.0
  -> python-pydbus
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
```
I'm not sure if this is something I'm doing wrong or if the PKGBUILD needs changed in some way, but I'm having trouble figuring this out and would really appreciate it if you had an idea on what to do

EDIT: Running vanilla Arch, and I ran `pacman -Syu` directly before this.

**Comment by mirsella** [comment]
hello, this package can't be installed with just pacman automatically as multiples python deps are only in the AUR. you need `yay` or `paru` or install all deps manually.

**Comment by alexdelorenzo** [comment]
Hi @FieryMewtwo, thanks for opening an issue.

A community member packaged this project for the AUR after my fumbled attempt at writing a good PKGBUILD. If you need help with the AUR package, please leave a comment on the AUR.
