### ISSUE TITLE
xesam:url is always empty on YouTube?

### ISSUE THREAD

**Issue by levihb** [alexdelorenzo/cast_control#8]
I would like to be able to grab the URL so I can quickly share something playing on my TV. But when I try grabbing metadata, `xesam:url` is always empty?

```
01:30:37 Levi-X330 ~ Σ playerctl metadata
Levis_TV mpris:trackid             '/track/A_tiny_joystick_for_pitch_bending'
Levis_TV mpris:length              485668000
Levis_TV mpris:artUrl              https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Chromecast_cast_button_icon.svg/500px-Chromecast_cast_button_icon.svg.png
Levis_TV xesam:url
Levis_TV xesam:title               A tiny joystick for pitch bending
Levis_TV xesam:artist              mitxela
Levis_TV xesam:albumArtist         mitxela
Levis_TV xesam:discNumber          1
```

Also if it's of any relevance, I'm using Google TV, the new Chromecast with a remote. And I'm using the YouTube app, not the cast app. Sending a URL to it works fine, and so does all other functionality.

**Comment by alexdelorenzo** [comment]
Thanks for opening an issue and including examples.

As of [v0.7.3](https://github.com/alexdelorenzo/chromecast_mpris/releases/tag/v0.7.3), `chromecast_mpris` will include YouTube URLs in its exported metadata when the URLs are available. You can install it with:

 ```base
$ python3 -m pip install chromecast_mpris==0.7.3 
```

> Also if it's of any relevance, I'm using Google TV, the new Chromecast with a remote. And I'm using the YouTube app, not the cast app. Sending a URL to it works fine, and so does all other functionality.

In my experience with the new Chromecast with Google TV, the YouTube app doesn't always provide complete metadata to PyChromecast. When I use the YouTube app with the remote that is often the case. Sometimes it works, though. Casting from my phone or via [catt](https://github.com/skorokithakis/catt) usually results in PyChromecast receiving the full metadata. 

`chromecast_mpris` uses PyChromecast to read the YouTube metadata, so it inherits this problem.

Either the YouTube app on the new Chromecast isn't reporting as much metadata as it used to on older models, or PyChromecast isn't receiving the metadata the app is supplying. 

I haven't looked into it, but this issue might be related to this bug: https://github.com/home-assistant-libs/pychromecast/issues/255

At some point I'm going to open an issue on their bug tracker, and I'll tag you when I do.

**Comment by alexdelorenzo** [comment]
I'm going to close this issue, feel free to comment or open it again if there are any updates.
